version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    ports:
      - 8080:8080
      - 4443:4443
      - 5900:5900
      - 6080:6080
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=4443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyAMA0
      - DECONZ_START_VERBOSE=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900